"""empty message

Revision ID: 72e6f4eb3fc8
Revises: 817d23abc0aa
Create Date: 2020-12-02 21:03:15.594697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e6f4eb3fc8'
down_revision = '817d23abc0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
