"""empty message

Revision ID: 817d23abc0aa
Revises: ab4471e7354e
Create Date: 2020-12-02 21:02:24.573012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817d23abc0aa'
down_revision = 'ab4471e7354e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
