"""add posts

Revision ID: ce17bff4c8f3
Revises: 72e6f4eb3fc8
Create Date: 2020-12-02 21:03:46.885405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce17bff4c8f3'
down_revision = '72e6f4eb3fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
